const path = require('path');
module.exports = {
  'react-router-redux-fixed': path.resolve('./src/common/react-router-redux-fixed.js'),
  SearchInput: path.resolve('./src/components/Common/SearchInput.jsx'),
  SupLabel: path.resolve('./src/components/Common/SupLabel.jsx'),
  TitleWithTools: path.resolve('./src/components/Common/TitleWithTools.jsx'),
  ShowHide: path.resolve('./src/components/ShowHide/index.jsx'),
  SearchPanel: path.resolve('./src/components/Common/SearchPanel.jsx'),
  SearchPanelNew: path.resolve('./src/components/Common/SearchPanelNew.jsx'),
  FullPagePanel: path.resolve('./src/components/FullPagePanel/index.jsx'),
  DataHeader: path.resolve('./src/components/Common/DataHeader.jsx'),
  StateMark: path.resolve('./src/components/Common/StateMark.jsx'),
  MianBao: path.resolve('./src/components/MianBao/index.jsx'),
  AppAction: path.resolve('./src/apps/action.js'),
  ProjectTree: path.resolve('./src/components/Common/ProjectTree.jsx'),
  MsgBox: path.resolve('./src/components/MsgBox/index.jsx'),
  util: path.resolve('./src/util/index.js'),
  enhanceUtil: path.resolve('./src/util/enhanceUtil.js'),
  ProTreSelect: path.resolve('./src/components/Common/ProjectTreeSelect.jsx'),
  BldTreeSelect: path.resolve('./src/components/Common/BldTreeSelect.jsx'),
  BldTreeSelectNoDaf: path.resolve('./src/components/Common/BldTreeSelectNoDaf.jsx'),
  ProCascader: path.resolve('./src/components/Common/ProjectCascader.jsx'),
  DictItemSelect: path.resolve('./src/components/Common/DictItemSelect.jsx'),
  BigProjSelect: path.resolve('./src/components/Common/BigProjSelect.jsx'),
  BigProjToCheckBoxSelectBld: path.resolve('./src/components/Common/BigProjToCheckBoxSelectBld.jsx'),
  BigProjToRaioSelect: path.resolve('./src/components/Common/BigProjToRaioSelect.jsx'),
  DictItemDisplay: path.resolve('./src/components/Common/DictItemDisplay.jsx'),
  CommonParamSelect: path.resolve('./src/components/Common/CommonParamSelect.jsx'),
  CommonProductSelect: path.resolve('./src/components/Common/CommonProductSelect.jsx'),
  SysIcon: path.resolve('./src/components/SysIcon/index.jsx'),
  Buttons: path.resolve('./src/components/Buttons/index.js'),
  JCFWSelect: path.resolve('./src/components/Common/JCFWSelect.jsx'),
  RoomSelect: path.resolve('./src/components/Common/RoomSelect.jsx'),
  OrgTreeModal: path.resolve('./src/components/Common/OrgTreeModal.jsx'),
  OrgTreeSelect: path.resolve('./src/components/Common/OrgTreeSelect.jsx'),
  EditTabs: path.resolve('./src/components/Common/EditTabs.jsx'),
  ChooseUserModal: path.resolve('./src/components/Common/ChooseUserModal.jsx'),
  TradeItemSelect: path.resolve('./src/components/Common/TradeItemSelect.jsx'),
  Salesman: path.resolve('./src/components/Common/Salesman.jsx'),
  ProjectUserSelect: path.resolve('./src/components/Common/ProjectUserSelect.jsx'),
  OrgStationSelect: path.resolve('./src/components/Common/OrgStationSelect.jsx'),
  xFetch: path.resolve('./src/util/xFetch.js'),
  // 'dict-util': path.resolve('./src/apps/saleMgr/dict-util.js'),
  ProjBldTree: path.resolve('./src/components/Common/ProjBldTree.jsx'),
  TagsSearch: path.resolve('./src/components/Common/TagsSearch.jsx'),
  ProjSelect: path.resolve('./src/components/Common/ProjectSelect.jsx'),
  RoomTreeByBld: path.resolve('./src/components/buildTree/roomTree.js')
}
